### PR TITLE
resending queue clear function added

### PR DESCRIPTION
**Pull request by AnttiKauppila**

### CODE REVIEW

**Comment by AnttiKauppila** [comment]
Good point, Thanks Antti. I also updated missing grs unittests in same go

**Comment by AnttiKauppila** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by AnttiKauppila** [comment]
rebuild

**Comment by AnttiKauppila** [comment]
@anttiylitokola is studying failure cases and said it is ok to merge this in

**Pull request merged**
