### PR TITLE
Fixed Coap resending error handling properly.

### PR DESCRIPTION
**Pull request by juhhei01**
Confirmable messge send will be stopped if resend storing return error.

### CODE REVIEW

**Comment by juhhei01** [comment]
@AnttiKauppila @terhei Can you review this

**Comment by juhhei01** [comment]
This could be added to master also I think.

**Comment by juhhei01** [comment]
I'm not big fan fan that uri path is allocated separately than message structure. It will fragment memory. We could allocated 1 pointer sizeof(message) + uri_length That will simplify many things and save a RAM

**Comment by kuggenhoffen** [comment]
@anttiylitokola Might be good to merge to master as well

**Comment by juhhei01** [comment]
PR for nanomesh4-rel looks be broken. Those failing cases are tested against mater

**Pull request merged**
