### PR TITLE
Multicast message resend to improve reliability mirrored #51

### PR DESCRIPTION
**Pull request by EduardPon**

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by yogpan01** [comment]
Hi @EduardPon,
Can you check my last comments on https://github.com/ARMmbed/mbed-client-c/issues/45 , please let us know if that would resolve your issue. We can then take action accordingly. It may be that we need not even have to take this PR but fix the existing solution.

**Comment by jankii01** [comment]
Hi,

@EduardPon  - can you confirm the fix done

https://github.com/ARMmbed/mbed-client-c/pull/77

 to enable duplication by default is enough? This branch has gone a bit cold and I wonder if  it's obsolete and we could close it?

**Comment by EduardPon** [comment]
Yes it is, thanks.

**Pull request closed without merging**
