### PR TITLE
Initialize options list after allocation

### PR DESCRIPTION
**Pull request by anttiylitokola**
Fix error IOTCLT-842 - Client crashes on sending coap_message with testcase I0010110F062

### CODE REVIEW

**Comment by anttiylitokola** [comment]
@yogpan01, @teetak01

**Comment by teetak01** [comment]
+1 Fixes several failing testcases on both yotta and morpheus.

**Comment by kjbracey-arm** [comment]
This is another thing already fixed more thoroughly in that pending code of mine (now PR #67, not that it's currently remotely mergeable, being about a year old).

**Comment by yogpan01** [comment]
+1

**Comment by kjbracey-arm** [comment]
Actually, given that it's the first commit of #67, and hence stand-alone, I'd say you may as well rebase and take that in, rather than do a minor partial fix like this.

**Comment by anttiylitokola** [comment]
@yogpan01, what do you think, should I spend few hours and take following commit in https://github.com/ARMmbed/mbed-client-c/pull/67/commits/0120645b264354f7b872178c64b6f57db4e5acb6?

**Comment by anttiylitokola** [comment]
@yogpan01, can you check this? We should get the static resource fix in.

**Comment by yogpan01** [comment]
@kjbracey-arm The changes done on #67 causes public coap structure to change which has direct impact on components using this. This will result in components for e.g: mbed-client , being incompatible with this change.

**Comment by anttiylitokola** [comment]
Changes done in this PR does not cause any API breaks. I have only merged one commit(https://github.com/ARMmbed/mbed-client-c/pull/67/commits/0120645b264354f7b872178c64b6f57db4e5acb6) which doesn't cause any breaks. However if we are going to take rest of the changes in then the API will change.

**Comment by yogpan01** [comment]
@anttiylitokola  I am talking about all the other commits changes which are part of #67

**Comment by kjbracey-arm** [comment]
Yes, #67 is a big API change, which is why it's been parked for a year waiting for someone to deal with it.

But the first commit (or its equivalent) is what we're talking about taking here. No API change there. (Apart from extending it so people don't have to do the alloc+clear combo themselves).

The main reason for stopping people doing the alloc clear combo is to allow the clear to have non-zero defaults for the later changes in the PR, but it also deals more thoroughly with the issue here.

If cherry-picking it, you should also search for any new alloc+clear occurrences, and get them to use the new APIs too.

**Comment by kjbracey-arm** [comment]
Was this a cherry-pick, or done manually in some way? Can you assure that the (majority) of the stuff transferred was transferred accurately (spacing etc)?

That'll be important when it comes to minimising conflicts when/if people try to apply the rest of PR#67.

**Comment by anttiylitokola** [comment]
I skip the cherry-pick part and did it manually using compare tool, I feel it much easier since the code base was changed so much. But the spacing etc. should be correctly transferred.

**Comment by kjbracey-arm** [comment]
If using a proper Git mergetool like P4Merge (my favourite) to deal with conflicts, usually automatic is easier. But thanks for taking care.

**Pull request merged**
