### PR TITLE
Update sn_grs.h

### PR DESCRIPTION
**Pull request by teetak01**
add ns_types.h to fix armcc compilation issue

### CODE REVIEW

**Comment by yogpan01** [comment]
@teetak01 Which build is this failing on?

**Comment by kjbracey-arm** [comment]
Not very logical - generally you should be writing headers with 1 of 2 assumptions:

1) All necessary dependencies and types are already included beforehand
2) You include all necessary headers yourself (or provide forward references).

If you're going to start including headers, you should be including everything you need - in this case ns_types, ns_list and sn_nsdl_lib.h. (Maybe omitting lower level ones if you know for a fact the higher level ones must be including the lower-level ones).

I can't immediately think how this change can fix anything - if ns_list and sn_resource_info_s were available, ns_types.h must have already been included?

**Comment by teetak01** [comment]
ARMCC compilation of mbed Client is currently failing, possibly due to recent update in CI ARMCC compiler. I was checking if it can be easily fixed by adding a new include the offending header.

**Comment by kjbracey-arm** [comment]
So this is a untested experimental pull request just to trigger a CI build? I can see why that's useful, but probably worth flagging that in some way to save people reviewing it. Is there a marker for it?

**Comment by teetak01** [comment]
Sorry, will test this elsewhere. Maybe we could specify Do Not Merge flags for all repos.

**Pull request closed without merging**
