### PR TITLE
Merge nanomesh4-rel branch

### PR DESCRIPTION
**Pull request by kjbracey-arm**
Only functional change is "convert_uri added to put method" (5ea430a5) by @AnttiKauppila.

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
@yogpan01, @TeroJaasko 

Do I gather the tests don't work if issuing a pull request from a fork?

**Comment by TeroJaasko** [comment]
@kjbracey-arm - the forking seems to be the cause of problems. The Jenkins job seems to first fetch from fork (refs/pull/87/merge:refs/remotes/origin-pull/pull/87/merge) properly and it gets the correct source from mbed-client-c. But then it fetches the mbed-client-testapp, which contains its own mbed-client-c.lib -> the hash is not there.

**Comment by kjbracey-arm** [comment]
So...

Fix the tests, or let me push directly so I don't have to fork?

**Comment by anttiylitokola** [comment]
If you could directly push it would solve the issue. Jenkins does not store the fork information with this new github-plugin and that's the reason why checkout fails in tests.

**Comment by yogpan01** [comment]
@kjbracey-arm  Please create a PR from this remote repo rather than your own fork, that will trigger CI jobs and we can see the results of the smoke tests.

**Comment by kjbracey-arm** [comment]
Repository permissions are locked down enough that I don't have access.

If you can't handle merges from forks, suggest opening up push access to at least all of Oulu.

**Comment by kjbracey-arm** [comment]
@AnttiKauppila - can you deal with this, seeing as it's only your commit?

**Comment by kjbracey-arm** [comment]
Any progress on this, @AnttiKauppila, @yogpan01?

**Comment by kjbracey-arm** [comment]
Okay, permissions for this repo found.

**Comment by kjbracey-arm** [comment]
Attempting pull request again without the fork in #88

**Pull request closed without merging**
