### PR TITLE
Coap option tidy

### PR DESCRIPTION
**Pull request by kjbracey-arm**
@artokin 

Here's that old work from Gerrit. (Miss you, Gerrit...)

### CODE REVIEW

**Comment by yogpan01** [comment]
@kjbracey-arm I am closing this PR as your changes are merged through https://github.com/ARMmbed/mbed-client-c/pull/75
Is it ok ?

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by kjbracey-arm** [comment]
Yeah, think so. The last 3 commits weren't taken, but they were more "thoughts" than finished work.

**Comment by yogpan01** [comment]
thanks ! I am closing this for now

**Pull request closed without merging**
