### PR TITLE
Introduced build time flag YOTTA_CFG_DISABLE_OBS_FEATURE

### PR DESCRIPTION
**Pull request by yogpan01**
This flag when enabled , will NOT send "obs" parameter as part of registration message.

### CODE REVIEW

**Comment by yogpan01** [comment]
@autopulated @ansondtx20 @anttiylitokola : Fix for managing different LWM2M server registration messages without messing existing implementation for Connector service.

**Comment by autopulated** [comment]
I don't believe this is the correct solution here.

We should be doing what the standard says, if the standard says our service implementation should change, then that's what we should change. Introducing an option will only introduce more possibilities to configure things incorrectly.

**Comment by yogpan01** [comment]
This needs someone from server team to verify if sending "obs" parameter as part of registration message defined in some specification.
@szysas @KalleVayrynen @norbert-david Guys can you please confirm , if this "obs" parameter sending defined in some specs or is it our own design.
Issue is some of the LWM2M servers reject registration messages if that contains anything other than Resource Structure.

@autopulated I think we would still need this solution, if we want to maintain backward compatibility of our existing solution. With this solution, our existing and future customers need not change anything but if some of them wants to use mbed-client against other stricter LWM2M servers, our client provides  them means to do it without them modifying anything on mbed-client itself.

**Comment by szysas** [comment]
It is defined here: https://tools.ietf.org/html/rfc7641#section-6

Szymon

**Comment by autopulated** [comment]
It'd be reasonable to do this for compatibility, but I think it'd better to do the hard work for compatibility server-side, if that's possible.

**Comment by yogpan01** [comment]
IMO, our e2e design in faulty when it comes to observation feature. Our design states that its the client which decides which resources can support observation feature, however it should be other way round, services can decide which resource they would like to observe and client should simply accept those and start sending notification for changed values of the resources which service has marked under observation. This is what I saw in OMA test fest also and started with changing implementation where we would make the whole observation flag redundant on client side. Which means services are free to decide whichever resource they would like to observer (out of those which are registered) and client will simply start observation and notification on those resources. But, since now I see how our customer services have implemented their business logic on this observation, its not possible to tread back(at least on client side) without breaking their functionality. But, I would like to silently enable this feature on client side where we allow any resource to be under observation, even though application has not explicitly set it as "observable". Over the period of time, we can then deprecate the whole observation API.

**Comment by szysas** [comment]
Yeap, we have recently loosen up this requirement, so we do not require 'obs' in registration for each observable resource.

**Comment by yogpan01** [comment]
Yes, but our existing customers have already built their business logic around our old solution. We cannot be breaking their solution by our internal changes. For instance, I think it is MS or Converge which greps for "obs" keyword in the endpoint resource list and based on that decides whether to issue Subsription or not. Suddenly stopping to send that parameter breaks their solution. Its not easy to keep the backward compatibility if one customer has logic around legacy implementation and new customer requires newer functionality.

**Comment by kjbracey-arm** [comment]
Seems that both our client and server behaviour are correct - server doesn't require it, and client includes it as a hint, as the RFC permits.

If there are some 3rd-party servers that need it and some 3rd-party servers which barf on it, we can't satisfy both.

Do we know for certain that the presence of obs= is causing a problem? Not clear to me from IOTCLT-366.

We should only add a build option if we're certain obs= is the problem, we need to support that server, and we can't get them to make their server compliant.

**Comment by yogpan01** [comment]
@kjbracey-arm We had the problem identified with few servers in OMA TestFest where they didnt accept the incoming registration messages containing "obs" text. With this change, default is that "obs" will be sent but if any client wants to disable this feature then they can use this flag to remove "obs" text as part of registration message.

**Comment by szysas** [comment]
Did just quick check and there are three PMD warnings

**Comment by yogpan01** [comment]
I will merge this change in for closing our IOTCLT-366 error. I have tested that this is backward compatible and doesn't break the "obs" solution as it did earlier for some of existing users.
Please shout out loud if someone has any objection.

**Comment by ansondtx20** [comment]
I have to give a demo to the entire Israel office Thursday morning 10am Israel time.... any chance we can delay until after that? 


Regards,

Doug

**Comment by yogpan01** [comment]
rebuild

**Pull request merged**
