### PR TITLE
Add support for size2 option

### PR DESCRIPTION
**Pull request by anttiylitokola**

### CODE REVIEW

**Comment by anttiylitokola** [comment]
@yogpan01

**Comment by yogpan01** [comment]
This has to be tested on hardware as well.

**Comment by anttiylitokola** [comment]
Tested also with K64F.

**Comment by yogpan01** [comment]
+1

**Comment by kjbracey-arm** [comment]
Are you ever planning to finish off the work I handed over to actually support numbers properly as numbers?

The code's pretty horrible as it is, and every extra "number as byte strings" addition just digs you deeper into the hole. This would have been a lot simpler change if the previous work had been completed.

**Pull request merged**
