### PR TITLE
Added API for deleting one message from resending

### PR DESCRIPTION
**Pull request by terhei**
queue.

@mikter

### CODE REVIEW

**Comment by mikter** [comment]
ok

**Comment by terhei** [comment]
@yogpan01

**Comment by yogpan01** [comment]
@terhei Please add unit test for the new function

**Comment by terhei** [comment]
@yogpan01 unit tests added, please review.

**Comment by yogpan01** [comment]
@anttiylitokola Please check the CI job for mbed-client-c_smoke_tests_hw, it is currently broken

**Comment by anttiylitokola** [comment]
LGTM

**Pull request merged**
