### PR TITLE
Add application definable context to nsdl handle

### PR DESCRIPTION
**Pull request by kuggenhoffen**
Added a application definable context void pointer to nsdl structure as well as setter and getter API's for it. This is useful for example when interfacing with c++ objects where a pointer to object is set as the context, and in the callback functions the context pointer can be used to call methods for the correct instance of the c++ object.

### CODE REVIEW

**Comment by kuggenhoffen** [comment]
@anttiylitokola @AnttiKauppila @TeroJaasko @terhei

**Comment by kuggenhoffen** [comment]
See https://github.com/ARMmbed/mbed-client/pull/342 for mbed client usage proposal

**Comment by TeroJaasko** [comment]
+1. That cover letter kind of description on this PR would be nice to have in the documentation of context too. We already have too little of information on our doxygen why something exists and what is it useful for.

**Comment by kuggenhoffen** [comment]
rebuild

**Comment by kuggenhoffen** [comment]
rebuild

**Pull request merged**
