### PR TITLE
Changed sn_coap_protocol.c to use randLIB for random message ID.

### PR DESCRIPTION
**Pull request by simosillankorva**
randLIB now needed to build the coap library.

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
I had a quick look through this earlier - I think you can also drop the places where it skips message_id 0. There is one place it checks for message ID 0 in the API, but it seems that can also be dropped - I believe should just be looking at the message type (CON/NON always take a new ID, ACK/RST always echo incoming ID).

As long as the Yotta files are there, you should add randLIB to the JSON dependencies.

**Comment by yogpan01** [comment]
Does someone need to implement the randomization function for randlib_get_16bit() to return random number ?

**Comment by kjbracey-arm** [comment]
Someone needs to implement arm_random_module_init() and arm_random_seed_get() from mbed-client-randlib/platform/arm_hal_random.h. In mbed OS 5, they're implemented in nanostack_hal_mbed_cmsis_rtos.

Also randlib_add_seed() can be called at various points to add in more randomness on top of the  seed_get() returns. At the extreme, arm_random_seed_get() can return nothing, and that would be okay as long as enough randomness then got pushed in with randlib_add_seed().

Current state in mbed os 5, random_seed_get() is returning randomness from the hardware entropy source if available, else nothing. And at present, the Atmel radio driver is adding 8 bits of randomness from the radio, and Nanostack adds in the MAC address of every interface.

**Comment by simosillankorva** [comment]
rebuild

**Pull request merged**
