### PR TITLE
Release 3.0.4

### PR DESCRIPTION
**Pull request by kuggenhoffen**

### CODE REVIEW

**Comment by jankii01** [comment]
Failures in build due to some Jenkins issue. It's not able to check out the hash, which of course can't be true. Some of builds worked/passed, so that's proof the hash exists.

**Comment by jankii01** [comment]
rebuild

**Comment by jankii01** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by kuggenhoffen** [comment]
FYI, this shouldn't be merged, this is just for tests

**Comment by yogpan01** [comment]
I am closing this PR and this is not supposed to be merged as per comments from @kuggenhoffen

**Pull request closed without merging**
