### PR TITLE
Add flagging for interface_description_ptr

### PR DESCRIPTION
**Pull request by JaniSuonpera**

### CODE REVIEW

**Comment by JaniSuonpera** [comment]
There dependency to https://github.com/ARMmbed/mbed-client/pull/424

**Comment by anttiylitokola** [comment]
rebuild

**Comment by JanneKiiskila** [comment]
I think if the change is 
a) backwards compatible AND
b) we change the config files so, that it's ON by default - we could release it to master as well.

It's super critical to keep non-backwards compatible changes in memopt branch, but backwards compatible changes are a different thing in my humble opinion.

**Comment by TeroJaasko** [comment]
This should go into memory_optimizations branch first. The PR target branch can be changed, but you you must rebase your branch against memory_optimizations.

**Pull request closed without merging**
